// bindgen halflife/common/beamdef.h --allowlist-type "BEAM" -- --target=i686-unknown-linux-gnu
// -Ihalflife/{public,common,engine} -include mathlib.h -include const.h
// Keep everything before the generated part
// Set `beam_s` `flags` field to `FBEAM` bitflags type
// Remove `model_s` dummy struct and import `model_s` from com_model.rs
// Remove `particle_s` dummy struct and import `particle_s` from particledef.rs
// Remove `vec_t` and `vec3_t` and replace `vec3_t` with `[f32; 3]`
// Remove the unnecessary qualifiers `::std::os::raw::` and `::std::mem::`

#![allow(nonstandard_style)]

use std::mem::{align_of, offset_of, size_of};
use std::os::raw::*;

use super::com_model::model_s;
use super::particledef::particle_s;

use bitflags::bitflags;

bitflags! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
    pub struct FBEAM: i32 {
        const STARTENTITY   = 0x00000001;
        const ENDENTITY     = 0x00000002;
        const FADEIN        = 0x00000004;
        const FADEOUT       = 0x00000008;
        const SINENOISE     = 0x00000010;
        const SOLID         = 0x00000020;
        const SHADEIN       = 0x00000040;
        const SHADEOUT      = 0x00000080;
        const STARTVISIBLE  = 0x10000000;
        const ENDVISIBLE    = 0x20000000;
        const ISACTIVE      = 0x40000000;
        const FOREVER       = 0x80000000u32 as i32;
    }
}

/* automatically generated by rust-bindgen 0.72.1 */

#[doc = "\tCopyright (c) 1996-2002, Valve LLC. All rights reserved.\n\n\tThis product contains software technology licensed from Id\n\tSoftware, Inc. (\"Id Technology\").  Id Technology (c) 1996 Id Software, Inc.\n\tAll Rights Reserved.\n\n   Use, distribution, and modification of this source code and/or resulting\n   object code is restricted to non-commercial enhancements to products from\n   Valve LLC.  All other use, distribution, or modification is prohibited\n   without written permission from Valve LLC."]
pub type BEAM = beam_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct beam_s {
    pub next: *mut BEAM,
    pub type_: c_int,
    pub flags: FBEAM,
    pub source: [f32; 3],
    pub target: [f32; 3],
    pub delta: [f32; 3],
    pub t: f32,
    pub freq: f32,
    pub die: f32,
    pub width: f32,
    pub amplitude: f32,
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub brightness: f32,
    pub speed: f32,
    pub frameRate: f32,
    pub frame: f32,
    pub segments: c_int,
    pub startEntity: c_int,
    pub endEntity: c_int,
    pub modelIndex: c_int,
    pub frameCount: c_int,
    pub pFollowModel: *mut model_s,
    pub particles: *mut particle_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of beam_s"][size_of::<beam_s>() - 124usize];
    ["Alignment of beam_s"][align_of::<beam_s>() - 4usize];
    ["Offset of field: beam_s::next"][offset_of!(beam_s, next) - 0usize];
    ["Offset of field: beam_s::type_"][offset_of!(beam_s, type_) - 4usize];
    ["Offset of field: beam_s::flags"][offset_of!(beam_s, flags) - 8usize];
    ["Offset of field: beam_s::source"][offset_of!(beam_s, source) - 12usize];
    ["Offset of field: beam_s::target"][offset_of!(beam_s, target) - 24usize];
    ["Offset of field: beam_s::delta"][offset_of!(beam_s, delta) - 36usize];
    ["Offset of field: beam_s::t"][offset_of!(beam_s, t) - 48usize];
    ["Offset of field: beam_s::freq"][offset_of!(beam_s, freq) - 52usize];
    ["Offset of field: beam_s::die"][offset_of!(beam_s, die) - 56usize];
    ["Offset of field: beam_s::width"][offset_of!(beam_s, width) - 60usize];
    ["Offset of field: beam_s::amplitude"][offset_of!(beam_s, amplitude) - 64usize];
    ["Offset of field: beam_s::r"][offset_of!(beam_s, r) - 68usize];
    ["Offset of field: beam_s::g"][offset_of!(beam_s, g) - 72usize];
    ["Offset of field: beam_s::b"][offset_of!(beam_s, b) - 76usize];
    ["Offset of field: beam_s::brightness"][offset_of!(beam_s, brightness) - 80usize];
    ["Offset of field: beam_s::speed"][offset_of!(beam_s, speed) - 84usize];
    ["Offset of field: beam_s::frameRate"][offset_of!(beam_s, frameRate) - 88usize];
    ["Offset of field: beam_s::frame"][offset_of!(beam_s, frame) - 92usize];
    ["Offset of field: beam_s::segments"][offset_of!(beam_s, segments) - 96usize];
    ["Offset of field: beam_s::startEntity"][offset_of!(beam_s, startEntity) - 100usize];
    ["Offset of field: beam_s::endEntity"][offset_of!(beam_s, endEntity) - 104usize];
    ["Offset of field: beam_s::modelIndex"][offset_of!(beam_s, modelIndex) - 108usize];
    ["Offset of field: beam_s::frameCount"][offset_of!(beam_s, frameCount) - 112usize];
    ["Offset of field: beam_s::pFollowModel"][offset_of!(beam_s, pFollowModel) - 116usize];
    ["Offset of field: beam_s::particles"][offset_of!(beam_s, particles) - 120usize];
};
