// bindgen halflife/common/cl_entity.h --allowlist-type "cl_entity_s" --
// --target=i686-unknown-linux-gnu -Ihalflife/{public,common,engine,pm_shared} -include mathlib.h
// -include const.h
// Keep everything before the generated part
// Remove `mleaf_s` dummy struct and import `mleaf_s` from com_model.rs
// Remove `model_s` dummy struct and import `model_s` from com_model.rs
// Remove `mnode_s` dummy struct and import `mnode_s` from com_model.rs
// Remove generated `entity_state_t` import `entity_state_t` from entity_state.rs
// Remove `vec_t` and `vec3_t` and replace `vec3_t` with `[f32; 3]`
// Remove the unnecessary qualifiers `::std::os::raw::` and `::std::mem::`

#![allow(unused, nonstandard_style)]

use std::mem::{align_of, offset_of, size_of};
use std::os::raw::*;

use super::com_model::{mleaf_s, mnode_s, model_s};
use super::entity_state::entity_state_t;

/* automatically generated by rust-bindgen 0.72.1 */

#[doc = "\tCopyright (c) 1996-2002, Valve LLC. All rights reserved.\n\n\tThis product contains software technology licensed from Id\n\tSoftware, Inc. (\"Id Technology\").  Id Technology (c) 1996 Id Software, Inc.\n\tAll Rights Reserved.\n\n   Use, distribution, and modification of this source code and/or resulting\n   object code is restricted to non-commercial enhancements to products from\n   Valve LLC.  All other use, distribution, or modification is prohibited\n   without written permission from Valve LLC."]
pub type byte = c_uchar;
pub const qboolean_false_: qboolean = 0;
pub const qboolean_true_: qboolean = 1;
pub type qboolean = c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct color24 {
    pub r: byte,
    pub g: byte,
    pub b: byte,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of color24"][size_of::<color24>() - 3usize];
    ["Alignment of color24"][align_of::<color24>() - 1usize];
    ["Offset of field: color24::r"][offset_of!(color24, r) - 0usize];
    ["Offset of field: color24::g"][offset_of!(color24, g) - 1usize];
    ["Offset of field: color24::b"][offset_of!(color24, b) - 2usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct colorVec {
    pub r: c_uint,
    pub g: c_uint,
    pub b: c_uint,
    pub a: c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of colorVec"][size_of::<colorVec>() - 16usize];
    ["Alignment of colorVec"][align_of::<colorVec>() - 4usize];
    ["Offset of field: colorVec::r"][offset_of!(colorVec, r) - 0usize];
    ["Offset of field: colorVec::g"][offset_of!(colorVec, g) - 4usize];
    ["Offset of field: colorVec::b"][offset_of!(colorVec, b) - 8usize];
    ["Offset of field: colorVec::a"][offset_of!(colorVec, a) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct efrag_s {
    pub leaf: *mut mleaf_s,
    pub leafnext: *mut efrag_s,
    pub entity: *mut cl_entity_s,
    pub entnext: *mut efrag_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of efrag_s"][size_of::<efrag_s>() - 16usize];
    ["Alignment of efrag_s"][align_of::<efrag_s>() - 4usize];
    ["Offset of field: efrag_s::leaf"][offset_of!(efrag_s, leaf) - 0usize];
    ["Offset of field: efrag_s::leafnext"][offset_of!(efrag_s, leafnext) - 4usize];
    ["Offset of field: efrag_s::entity"][offset_of!(efrag_s, entity) - 8usize];
    ["Offset of field: efrag_s::entnext"][offset_of!(efrag_s, entnext) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mouth_t {
    pub mouthopen: byte,
    pub sndcount: byte,
    pub sndavg: c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mouth_t"][size_of::<mouth_t>() - 8usize];
    ["Alignment of mouth_t"][align_of::<mouth_t>() - 4usize];
    ["Offset of field: mouth_t::mouthopen"][offset_of!(mouth_t, mouthopen) - 0usize];
    ["Offset of field: mouth_t::sndcount"][offset_of!(mouth_t, sndcount) - 1usize];
    ["Offset of field: mouth_t::sndavg"][offset_of!(mouth_t, sndavg) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct latchedvars_t {
    pub prevanimtime: f32,
    pub sequencetime: f32,
    pub prevseqblending: [byte; 2usize],
    pub prevorigin: [f32; 3],
    pub prevangles: [f32; 3],
    pub prevsequence: c_int,
    pub prevframe: f32,
    pub prevcontroller: [byte; 4usize],
    pub prevblending: [byte; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of latchedvars_t"][size_of::<latchedvars_t>() - 52usize];
    ["Alignment of latchedvars_t"][align_of::<latchedvars_t>() - 4usize];
    ["Offset of field: latchedvars_t::prevanimtime"]
        [offset_of!(latchedvars_t, prevanimtime) - 0usize];
    ["Offset of field: latchedvars_t::sequencetime"]
        [offset_of!(latchedvars_t, sequencetime) - 4usize];
    ["Offset of field: latchedvars_t::prevseqblending"]
        [offset_of!(latchedvars_t, prevseqblending) - 8usize];
    ["Offset of field: latchedvars_t::prevorigin"][offset_of!(latchedvars_t, prevorigin) - 12usize];
    ["Offset of field: latchedvars_t::prevangles"][offset_of!(latchedvars_t, prevangles) - 24usize];
    ["Offset of field: latchedvars_t::prevsequence"]
        [offset_of!(latchedvars_t, prevsequence) - 36usize];
    ["Offset of field: latchedvars_t::prevframe"][offset_of!(latchedvars_t, prevframe) - 40usize];
    ["Offset of field: latchedvars_t::prevcontroller"]
        [offset_of!(latchedvars_t, prevcontroller) - 44usize];
    ["Offset of field: latchedvars_t::prevblending"]
        [offset_of!(latchedvars_t, prevblending) - 48usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct position_history_t {
    pub animtime: f32,
    pub origin: [f32; 3],
    pub angles: [f32; 3],
}

impl ::core::fmt::Debug for position_history_t {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(".")
    }
}

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of position_history_t"][size_of::<position_history_t>() - 28usize];
    ["Alignment of position_history_t"][align_of::<position_history_t>() - 4usize];
    ["Offset of field: position_history_t::animtime"]
        [offset_of!(position_history_t, animtime) - 0usize];
    ["Offset of field: position_history_t::origin"]
        [offset_of!(position_history_t, origin) - 4usize];
    ["Offset of field: position_history_t::angles"]
        [offset_of!(position_history_t, angles) - 16usize];
};
pub type cl_entity_t = cl_entity_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cl_entity_s {
    pub index: c_int,
    pub player: qboolean,
    pub baseline: entity_state_t,
    pub prevstate: entity_state_t,
    pub curstate: entity_state_t,
    pub current_position: c_int,
    pub ph: [position_history_t; 64usize],
    pub mouth: mouth_t,
    pub latched: latchedvars_t,
    pub lastmove: f32,
    pub origin: [f32; 3],
    pub angles: [f32; 3],
    pub attachment: [[f32; 3]; 4usize],
    pub trivial_accept: c_int,
    pub model: *mut model_s,
    pub efrag: *mut efrag_s,
    pub topnode: *mut mnode_s,
    pub syncbase: f32,
    pub visframe: c_int,
    pub cvFloorColor: colorVec,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cl_entity_s"][size_of::<cl_entity_s>() - 3000usize];
    ["Alignment of cl_entity_s"][align_of::<cl_entity_s>() - 4usize];
    ["Offset of field: cl_entity_s::index"][offset_of!(cl_entity_s, index) - 0usize];
    ["Offset of field: cl_entity_s::player"][offset_of!(cl_entity_s, player) - 4usize];
    ["Offset of field: cl_entity_s::baseline"][offset_of!(cl_entity_s, baseline) - 8usize];
    ["Offset of field: cl_entity_s::prevstate"][offset_of!(cl_entity_s, prevstate) - 348usize];
    ["Offset of field: cl_entity_s::curstate"][offset_of!(cl_entity_s, curstate) - 688usize];
    ["Offset of field: cl_entity_s::current_position"]
        [offset_of!(cl_entity_s, current_position) - 1028usize];
    ["Offset of field: cl_entity_s::ph"][offset_of!(cl_entity_s, ph) - 1032usize];
    ["Offset of field: cl_entity_s::mouth"][offset_of!(cl_entity_s, mouth) - 2824usize];
    ["Offset of field: cl_entity_s::latched"][offset_of!(cl_entity_s, latched) - 2832usize];
    ["Offset of field: cl_entity_s::lastmove"][offset_of!(cl_entity_s, lastmove) - 2884usize];
    ["Offset of field: cl_entity_s::origin"][offset_of!(cl_entity_s, origin) - 2888usize];
    ["Offset of field: cl_entity_s::angles"][offset_of!(cl_entity_s, angles) - 2900usize];
    ["Offset of field: cl_entity_s::attachment"][offset_of!(cl_entity_s, attachment) - 2912usize];
    ["Offset of field: cl_entity_s::trivial_accept"]
        [offset_of!(cl_entity_s, trivial_accept) - 2960usize];
    ["Offset of field: cl_entity_s::model"][offset_of!(cl_entity_s, model) - 2964usize];
    ["Offset of field: cl_entity_s::efrag"][offset_of!(cl_entity_s, efrag) - 2968usize];
    ["Offset of field: cl_entity_s::topnode"][offset_of!(cl_entity_s, topnode) - 2972usize];
    ["Offset of field: cl_entity_s::syncbase"][offset_of!(cl_entity_s, syncbase) - 2976usize];
    ["Offset of field: cl_entity_s::visframe"][offset_of!(cl_entity_s, visframe) - 2980usize];
    ["Offset of field: cl_entity_s::cvFloorColor"]
        [offset_of!(cl_entity_s, cvFloorColor) - 2984usize];
};
