// bindgen halflife/common/crc.h --allowlist-type "MD5Context_t|CRC32_t" --
// --target=i686-unknown-linux-gnu -Ihalflife/public
// Keep everything before the generated part
// Remove the unnecessary qualifiers `::std::os::raw::` and `::std::mem::`

#![allow(nonstandard_style)]

use std::mem::{align_of, offset_of, size_of};
use std::os::raw::*;

/* automatically generated by rust-bindgen 0.72.1 */

pub type uint32 = c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MD5Context_t {
    pub buf: [c_uint; 4usize],
    pub bits: [c_uint; 2usize],
    pub in_: [c_uchar; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of MD5Context_t"][size_of::<MD5Context_t>() - 88usize];
    ["Alignment of MD5Context_t"][align_of::<MD5Context_t>() - 4usize];
    ["Offset of field: MD5Context_t::buf"][offset_of!(MD5Context_t, buf) - 0usize];
    ["Offset of field: MD5Context_t::bits"][offset_of!(MD5Context_t, bits) - 16usize];
    ["Offset of field: MD5Context_t::in_"][offset_of!(MD5Context_t, in_) - 24usize];
};
pub type CRC32_t = uint32;
