// bindgen halflife/common/dlight.h --allowlist-type "dlight_t" -- --target=i686-unknown-linux-gnu
// -Ihalflife/{public,common,engine} -include mathlib.h -include const.h
// Keep everything before the generated part
// Remove `vec_t` and `vec3_t` and replace `vec3_t` with `[f32; 3]`
// Remove the unnecessary qualifiers `::std::os::raw::` and `::std::mem::`

#![allow(nonstandard_style)]

use std::mem::{align_of, offset_of, size_of};
use std::os::raw::*;

/* automatically generated by rust-bindgen 0.72.1 */

#[doc = "\tCopyright (c) 1996-2002, Valve LLC. All rights reserved.\n\n\tThis product contains software technology licensed from Id\n\tSoftware, Inc. (\"Id Technology\").  Id Technology (c) 1996 Id Software, Inc.\n\tAll Rights Reserved.\n\n   Use, distribution, and modification of this source code and/or resulting\n   object code is restricted to non-commercial enhancements to products from\n   Valve LLC.  All other use, distribution, or modification is prohibited\n   without written permission from Valve LLC."]
pub type byte = c_uchar;
pub const qboolean_false_: qboolean = 0;
pub const qboolean_true_: qboolean = 1;
pub type qboolean = c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct color24 {
    pub r: byte,
    pub g: byte,
    pub b: byte,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of color24"][size_of::<color24>() - 3usize];
    ["Alignment of color24"][align_of::<color24>() - 1usize];
    ["Offset of field: color24::r"][offset_of!(color24, r) - 0usize];
    ["Offset of field: color24::g"][offset_of!(color24, g) - 1usize];
    ["Offset of field: color24::b"][offset_of!(color24, b) - 2usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dlight_s {
    pub origin: [f32; 3],
    pub radius: f32,
    pub color: color24,
    pub die: f32,
    pub decay: f32,
    pub minlight: f32,
    pub key: c_int,
    pub dark: qboolean,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dlight_s"][size_of::<dlight_s>() - 40usize];
    ["Alignment of dlight_s"][align_of::<dlight_s>() - 4usize];
    ["Offset of field: dlight_s::origin"][offset_of!(dlight_s, origin) - 0usize];
    ["Offset of field: dlight_s::radius"][offset_of!(dlight_s, radius) - 12usize];
    ["Offset of field: dlight_s::color"][offset_of!(dlight_s, color) - 16usize];
    ["Offset of field: dlight_s::die"][offset_of!(dlight_s, die) - 20usize];
    ["Offset of field: dlight_s::decay"][offset_of!(dlight_s, decay) - 24usize];
    ["Offset of field: dlight_s::minlight"][offset_of!(dlight_s, minlight) - 28usize];
    ["Offset of field: dlight_s::key"][offset_of!(dlight_s, key) - 32usize];
    ["Offset of field: dlight_s::dark"][offset_of!(dlight_s, dark) - 36usize];
};
pub type dlight_t = dlight_s;
