// bindgen halflife/common/entity_state.h --allowlist-type "entity_state_t|clientdata_t" -- --target=i686-unknown-linux-gnu -Ihalflife/{public,common,engine,pm_shared} -include mathlib.h -include const.h
// Keep everything before the generated part
// Remove `vec_t` and `vec3_t` and replace `vec3_t` with `[f32; 3]`
// Remove the unnecessary qualifiers `::std::os::raw::` and `::std::mem::`
// added derive eq to color24
// FIXME: one color24 definition (and some others, probably)

#![allow(nonstandard_style)]

use std::mem::{align_of, offset_of, size_of};
use std::os::raw::*;

/* automatically generated by rust-bindgen 0.72.1 */

#[doc = "\tCopyright (c) 1996-2002, Valve LLC. All rights reserved.\n\n\tThis product contains software technology licensed from Id\n\tSoftware, Inc. (\"Id Technology\").  Id Technology (c) 1996 Id Software, Inc.\n\tAll Rights Reserved.\n\n   Use, distribution, and modification of this source code and/or resulting\n   object code is restricted to non-commercial enhancements to products from\n   Valve LLC.  All other use, distribution, or modification is prohibited\n   without written permission from Valve LLC."]
pub type byte = c_uchar;
pub const qboolean_false_: qboolean = 0;
pub const qboolean_true_: qboolean = 1;
pub type qboolean = c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub struct color24 {
    pub r: byte,
    pub g: byte,
    pub b: byte,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of color24"][size_of::<color24>() - 3usize];
    ["Alignment of color24"][align_of::<color24>() - 1usize];
    ["Offset of field: color24::r"][offset_of!(color24, r) - 0usize];
    ["Offset of field: color24::g"][offset_of!(color24, g) - 1usize];
    ["Offset of field: color24::b"][offset_of!(color24, b) - 2usize];
};
pub type entity_state_t = entity_state_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct entity_state_s {
    pub entityType: c_int,
    pub number: c_int,
    pub msg_time: f32,
    pub messagenum: c_int,
    pub origin: [f32; 3],
    pub angles: [f32; 3],
    pub modelindex: c_int,
    pub sequence: c_int,
    pub frame: f32,
    pub colormap: c_int,
    pub skin: c_short,
    pub solid: c_short,
    pub effects: c_int,
    pub scale: f32,
    pub eflags: byte,
    pub rendermode: c_int,
    pub renderamt: c_int,
    pub rendercolor: color24,
    pub renderfx: c_int,
    pub movetype: c_int,
    pub animtime: f32,
    pub framerate: f32,
    pub body: c_int,
    pub controller: [byte; 4usize],
    pub blending: [byte; 4usize],
    pub velocity: [f32; 3],
    pub mins: [f32; 3],
    pub maxs: [f32; 3],
    pub aiment: c_int,
    pub owner: c_int,
    pub friction: f32,
    pub gravity: f32,
    pub team: c_int,
    pub playerclass: c_int,
    pub health: c_int,
    pub spectator: qboolean,
    pub weaponmodel: c_int,
    pub gaitsequence: c_int,
    pub basevelocity: [f32; 3],
    pub usehull: c_int,
    pub oldbuttons: c_int,
    pub onground: c_int,
    pub iStepLeft: c_int,
    pub flFallVelocity: f32,
    pub fov: f32,
    pub weaponanim: c_int,
    pub startpos: [f32; 3],
    pub endpos: [f32; 3],
    pub impacttime: f32,
    pub starttime: f32,
    pub iuser1: c_int,
    pub iuser2: c_int,
    pub iuser3: c_int,
    pub iuser4: c_int,
    pub fuser1: f32,
    pub fuser2: f32,
    pub fuser3: f32,
    pub fuser4: f32,
    pub vuser1: [f32; 3],
    pub vuser2: [f32; 3],
    pub vuser3: [f32; 3],
    pub vuser4: [f32; 3],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of entity_state_s"][size_of::<entity_state_s>() - 340usize];
    ["Alignment of entity_state_s"][align_of::<entity_state_s>() - 4usize];
    ["Offset of field: entity_state_s::entityType"]
        [offset_of!(entity_state_s, entityType) - 0usize];
    ["Offset of field: entity_state_s::number"][offset_of!(entity_state_s, number) - 4usize];
    ["Offset of field: entity_state_s::msg_time"][offset_of!(entity_state_s, msg_time) - 8usize];
    ["Offset of field: entity_state_s::messagenum"]
        [offset_of!(entity_state_s, messagenum) - 12usize];
    ["Offset of field: entity_state_s::origin"][offset_of!(entity_state_s, origin) - 16usize];
    ["Offset of field: entity_state_s::angles"][offset_of!(entity_state_s, angles) - 28usize];
    ["Offset of field: entity_state_s::modelindex"]
        [offset_of!(entity_state_s, modelindex) - 40usize];
    ["Offset of field: entity_state_s::sequence"][offset_of!(entity_state_s, sequence) - 44usize];
    ["Offset of field: entity_state_s::frame"][offset_of!(entity_state_s, frame) - 48usize];
    ["Offset of field: entity_state_s::colormap"][offset_of!(entity_state_s, colormap) - 52usize];
    ["Offset of field: entity_state_s::skin"][offset_of!(entity_state_s, skin) - 56usize];
    ["Offset of field: entity_state_s::solid"][offset_of!(entity_state_s, solid) - 58usize];
    ["Offset of field: entity_state_s::effects"][offset_of!(entity_state_s, effects) - 60usize];
    ["Offset of field: entity_state_s::scale"][offset_of!(entity_state_s, scale) - 64usize];
    ["Offset of field: entity_state_s::eflags"][offset_of!(entity_state_s, eflags) - 68usize];
    ["Offset of field: entity_state_s::rendermode"]
        [offset_of!(entity_state_s, rendermode) - 72usize];
    ["Offset of field: entity_state_s::renderamt"][offset_of!(entity_state_s, renderamt) - 76usize];
    ["Offset of field: entity_state_s::rendercolor"]
        [offset_of!(entity_state_s, rendercolor) - 80usize];
    ["Offset of field: entity_state_s::renderfx"][offset_of!(entity_state_s, renderfx) - 84usize];
    ["Offset of field: entity_state_s::movetype"][offset_of!(entity_state_s, movetype) - 88usize];
    ["Offset of field: entity_state_s::animtime"][offset_of!(entity_state_s, animtime) - 92usize];
    ["Offset of field: entity_state_s::framerate"][offset_of!(entity_state_s, framerate) - 96usize];
    ["Offset of field: entity_state_s::body"][offset_of!(entity_state_s, body) - 100usize];
    ["Offset of field: entity_state_s::controller"]
        [offset_of!(entity_state_s, controller) - 104usize];
    ["Offset of field: entity_state_s::blending"][offset_of!(entity_state_s, blending) - 108usize];
    ["Offset of field: entity_state_s::velocity"][offset_of!(entity_state_s, velocity) - 112usize];
    ["Offset of field: entity_state_s::mins"][offset_of!(entity_state_s, mins) - 124usize];
    ["Offset of field: entity_state_s::maxs"][offset_of!(entity_state_s, maxs) - 136usize];
    ["Offset of field: entity_state_s::aiment"][offset_of!(entity_state_s, aiment) - 148usize];
    ["Offset of field: entity_state_s::owner"][offset_of!(entity_state_s, owner) - 152usize];
    ["Offset of field: entity_state_s::friction"][offset_of!(entity_state_s, friction) - 156usize];
    ["Offset of field: entity_state_s::gravity"][offset_of!(entity_state_s, gravity) - 160usize];
    ["Offset of field: entity_state_s::team"][offset_of!(entity_state_s, team) - 164usize];
    ["Offset of field: entity_state_s::playerclass"]
        [offset_of!(entity_state_s, playerclass) - 168usize];
    ["Offset of field: entity_state_s::health"][offset_of!(entity_state_s, health) - 172usize];
    ["Offset of field: entity_state_s::spectator"]
        [offset_of!(entity_state_s, spectator) - 176usize];
    ["Offset of field: entity_state_s::weaponmodel"]
        [offset_of!(entity_state_s, weaponmodel) - 180usize];
    ["Offset of field: entity_state_s::gaitsequence"]
        [offset_of!(entity_state_s, gaitsequence) - 184usize];
    ["Offset of field: entity_state_s::basevelocity"]
        [offset_of!(entity_state_s, basevelocity) - 188usize];
    ["Offset of field: entity_state_s::usehull"][offset_of!(entity_state_s, usehull) - 200usize];
    ["Offset of field: entity_state_s::oldbuttons"]
        [offset_of!(entity_state_s, oldbuttons) - 204usize];
    ["Offset of field: entity_state_s::onground"][offset_of!(entity_state_s, onground) - 208usize];
    ["Offset of field: entity_state_s::iStepLeft"]
        [offset_of!(entity_state_s, iStepLeft) - 212usize];
    ["Offset of field: entity_state_s::flFallVelocity"]
        [offset_of!(entity_state_s, flFallVelocity) - 216usize];
    ["Offset of field: entity_state_s::fov"][offset_of!(entity_state_s, fov) - 220usize];
    ["Offset of field: entity_state_s::weaponanim"]
        [offset_of!(entity_state_s, weaponanim) - 224usize];
    ["Offset of field: entity_state_s::startpos"][offset_of!(entity_state_s, startpos) - 228usize];
    ["Offset of field: entity_state_s::endpos"][offset_of!(entity_state_s, endpos) - 240usize];
    ["Offset of field: entity_state_s::impacttime"]
        [offset_of!(entity_state_s, impacttime) - 252usize];
    ["Offset of field: entity_state_s::starttime"]
        [offset_of!(entity_state_s, starttime) - 256usize];
    ["Offset of field: entity_state_s::iuser1"][offset_of!(entity_state_s, iuser1) - 260usize];
    ["Offset of field: entity_state_s::iuser2"][offset_of!(entity_state_s, iuser2) - 264usize];
    ["Offset of field: entity_state_s::iuser3"][offset_of!(entity_state_s, iuser3) - 268usize];
    ["Offset of field: entity_state_s::iuser4"][offset_of!(entity_state_s, iuser4) - 272usize];
    ["Offset of field: entity_state_s::fuser1"][offset_of!(entity_state_s, fuser1) - 276usize];
    ["Offset of field: entity_state_s::fuser2"][offset_of!(entity_state_s, fuser2) - 280usize];
    ["Offset of field: entity_state_s::fuser3"][offset_of!(entity_state_s, fuser3) - 284usize];
    ["Offset of field: entity_state_s::fuser4"][offset_of!(entity_state_s, fuser4) - 288usize];
    ["Offset of field: entity_state_s::vuser1"][offset_of!(entity_state_s, vuser1) - 292usize];
    ["Offset of field: entity_state_s::vuser2"][offset_of!(entity_state_s, vuser2) - 304usize];
    ["Offset of field: entity_state_s::vuser3"][offset_of!(entity_state_s, vuser3) - 316usize];
    ["Offset of field: entity_state_s::vuser4"][offset_of!(entity_state_s, vuser4) - 328usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clientdata_s {
    pub origin: [f32; 3],
    pub velocity: [f32; 3],
    pub viewmodel: c_int,
    pub punchangle: [f32; 3],
    pub flags: c_int,
    pub waterlevel: c_int,
    pub watertype: c_int,
    pub view_ofs: [f32; 3],
    pub health: f32,
    pub bInDuck: c_int,
    pub weapons: c_int,
    pub flTimeStepSound: c_int,
    pub flDuckTime: c_int,
    pub flSwimTime: c_int,
    pub waterjumptime: c_int,
    pub maxspeed: f32,
    pub fov: f32,
    pub weaponanim: c_int,
    pub m_iId: c_int,
    pub ammo_shells: c_int,
    pub ammo_nails: c_int,
    pub ammo_cells: c_int,
    pub ammo_rockets: c_int,
    pub m_flNextAttack: f32,
    pub tfstate: c_int,
    pub pushmsec: c_int,
    pub deadflag: c_int,
    pub physinfo: [c_char; 256usize],
    pub iuser1: c_int,
    pub iuser2: c_int,
    pub iuser3: c_int,
    pub iuser4: c_int,
    pub fuser1: f32,
    pub fuser2: f32,
    pub fuser3: f32,
    pub fuser4: f32,
    pub vuser1: [f32; 3],
    pub vuser2: [f32; 3],
    pub vuser3: [f32; 3],
    pub vuser4: [f32; 3],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of clientdata_s"][size_of::<clientdata_s>() - 476usize];
    ["Alignment of clientdata_s"][align_of::<clientdata_s>() - 4usize];
    ["Offset of field: clientdata_s::origin"][offset_of!(clientdata_s, origin) - 0usize];
    ["Offset of field: clientdata_s::velocity"][offset_of!(clientdata_s, velocity) - 12usize];
    ["Offset of field: clientdata_s::viewmodel"][offset_of!(clientdata_s, viewmodel) - 24usize];
    ["Offset of field: clientdata_s::punchangle"][offset_of!(clientdata_s, punchangle) - 28usize];
    ["Offset of field: clientdata_s::flags"][offset_of!(clientdata_s, flags) - 40usize];
    ["Offset of field: clientdata_s::waterlevel"][offset_of!(clientdata_s, waterlevel) - 44usize];
    ["Offset of field: clientdata_s::watertype"][offset_of!(clientdata_s, watertype) - 48usize];
    ["Offset of field: clientdata_s::view_ofs"][offset_of!(clientdata_s, view_ofs) - 52usize];
    ["Offset of field: clientdata_s::health"][offset_of!(clientdata_s, health) - 64usize];
    ["Offset of field: clientdata_s::bInDuck"][offset_of!(clientdata_s, bInDuck) - 68usize];
    ["Offset of field: clientdata_s::weapons"][offset_of!(clientdata_s, weapons) - 72usize];
    ["Offset of field: clientdata_s::flTimeStepSound"]
        [offset_of!(clientdata_s, flTimeStepSound) - 76usize];
    ["Offset of field: clientdata_s::flDuckTime"][offset_of!(clientdata_s, flDuckTime) - 80usize];
    ["Offset of field: clientdata_s::flSwimTime"][offset_of!(clientdata_s, flSwimTime) - 84usize];
    ["Offset of field: clientdata_s::waterjumptime"]
        [offset_of!(clientdata_s, waterjumptime) - 88usize];
    ["Offset of field: clientdata_s::maxspeed"][offset_of!(clientdata_s, maxspeed) - 92usize];
    ["Offset of field: clientdata_s::fov"][offset_of!(clientdata_s, fov) - 96usize];
    ["Offset of field: clientdata_s::weaponanim"][offset_of!(clientdata_s, weaponanim) - 100usize];
    ["Offset of field: clientdata_s::m_iId"][offset_of!(clientdata_s, m_iId) - 104usize];
    ["Offset of field: clientdata_s::ammo_shells"]
        [offset_of!(clientdata_s, ammo_shells) - 108usize];
    ["Offset of field: clientdata_s::ammo_nails"][offset_of!(clientdata_s, ammo_nails) - 112usize];
    ["Offset of field: clientdata_s::ammo_cells"][offset_of!(clientdata_s, ammo_cells) - 116usize];
    ["Offset of field: clientdata_s::ammo_rockets"]
        [offset_of!(clientdata_s, ammo_rockets) - 120usize];
    ["Offset of field: clientdata_s::m_flNextAttack"]
        [offset_of!(clientdata_s, m_flNextAttack) - 124usize];
    ["Offset of field: clientdata_s::tfstate"][offset_of!(clientdata_s, tfstate) - 128usize];
    ["Offset of field: clientdata_s::pushmsec"][offset_of!(clientdata_s, pushmsec) - 132usize];
    ["Offset of field: clientdata_s::deadflag"][offset_of!(clientdata_s, deadflag) - 136usize];
    ["Offset of field: clientdata_s::physinfo"][offset_of!(clientdata_s, physinfo) - 140usize];
    ["Offset of field: clientdata_s::iuser1"][offset_of!(clientdata_s, iuser1) - 396usize];
    ["Offset of field: clientdata_s::iuser2"][offset_of!(clientdata_s, iuser2) - 400usize];
    ["Offset of field: clientdata_s::iuser3"][offset_of!(clientdata_s, iuser3) - 404usize];
    ["Offset of field: clientdata_s::iuser4"][offset_of!(clientdata_s, iuser4) - 408usize];
    ["Offset of field: clientdata_s::fuser1"][offset_of!(clientdata_s, fuser1) - 412usize];
    ["Offset of field: clientdata_s::fuser2"][offset_of!(clientdata_s, fuser2) - 416usize];
    ["Offset of field: clientdata_s::fuser3"][offset_of!(clientdata_s, fuser3) - 420usize];
    ["Offset of field: clientdata_s::fuser4"][offset_of!(clientdata_s, fuser4) - 424usize];
    ["Offset of field: clientdata_s::vuser1"][offset_of!(clientdata_s, vuser1) - 428usize];
    ["Offset of field: clientdata_s::vuser2"][offset_of!(clientdata_s, vuser2) - 440usize];
    ["Offset of field: clientdata_s::vuser3"][offset_of!(clientdata_s, vuser3) - 452usize];
    ["Offset of field: clientdata_s::vuser4"][offset_of!(clientdata_s, vuser4) - 464usize];
};
pub type clientdata_t = clientdata_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct weapon_data_s {
    pub m_iId: c_int,
    pub m_iClip: c_int,
    pub m_flNextPrimaryAttack: f32,
    pub m_flNextSecondaryAttack: f32,
    pub m_flTimeWeaponIdle: f32,
    pub m_fInReload: c_int,
    pub m_fInSpecialReload: c_int,
    pub m_flNextReload: f32,
    pub m_flPumpTime: f32,
    pub m_fReloadTime: f32,
    pub m_fAimedDamage: f32,
    pub m_fNextAimBonus: f32,
    pub m_fInZoom: c_int,
    pub m_iWeaponState: c_int,
    pub iuser1: c_int,
    pub iuser2: c_int,
    pub iuser3: c_int,
    pub iuser4: c_int,
    pub fuser1: f32,
    pub fuser2: f32,
    pub fuser3: f32,
    pub fuser4: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of weapon_data_s"][size_of::<weapon_data_s>() - 88usize];
    ["Alignment of weapon_data_s"][align_of::<weapon_data_s>() - 4usize];
    ["Offset of field: weapon_data_s::m_iId"][offset_of!(weapon_data_s, m_iId) - 0usize];
    ["Offset of field: weapon_data_s::m_iClip"][offset_of!(weapon_data_s, m_iClip) - 4usize];
    ["Offset of field: weapon_data_s::m_flNextPrimaryAttack"]
        [offset_of!(weapon_data_s, m_flNextPrimaryAttack) - 8usize];
    ["Offset of field: weapon_data_s::m_flNextSecondaryAttack"]
        [offset_of!(weapon_data_s, m_flNextSecondaryAttack) - 12usize];
    ["Offset of field: weapon_data_s::m_flTimeWeaponIdle"]
        [offset_of!(weapon_data_s, m_flTimeWeaponIdle) - 16usize];
    ["Offset of field: weapon_data_s::m_fInReload"]
        [offset_of!(weapon_data_s, m_fInReload) - 20usize];
    ["Offset of field: weapon_data_s::m_fInSpecialReload"]
        [offset_of!(weapon_data_s, m_fInSpecialReload) - 24usize];
    ["Offset of field: weapon_data_s::m_flNextReload"]
        [offset_of!(weapon_data_s, m_flNextReload) - 28usize];
    ["Offset of field: weapon_data_s::m_flPumpTime"]
        [offset_of!(weapon_data_s, m_flPumpTime) - 32usize];
    ["Offset of field: weapon_data_s::m_fReloadTime"]
        [offset_of!(weapon_data_s, m_fReloadTime) - 36usize];
    ["Offset of field: weapon_data_s::m_fAimedDamage"]
        [offset_of!(weapon_data_s, m_fAimedDamage) - 40usize];
    ["Offset of field: weapon_data_s::m_fNextAimBonus"]
        [offset_of!(weapon_data_s, m_fNextAimBonus) - 44usize];
    ["Offset of field: weapon_data_s::m_fInZoom"][offset_of!(weapon_data_s, m_fInZoom) - 48usize];
    ["Offset of field: weapon_data_s::m_iWeaponState"]
        [offset_of!(weapon_data_s, m_iWeaponState) - 52usize];
    ["Offset of field: weapon_data_s::iuser1"][offset_of!(weapon_data_s, iuser1) - 56usize];
    ["Offset of field: weapon_data_s::iuser2"][offset_of!(weapon_data_s, iuser2) - 60usize];
    ["Offset of field: weapon_data_s::iuser3"][offset_of!(weapon_data_s, iuser3) - 64usize];
    ["Offset of field: weapon_data_s::iuser4"][offset_of!(weapon_data_s, iuser4) - 68usize];
    ["Offset of field: weapon_data_s::fuser1"][offset_of!(weapon_data_s, fuser1) - 72usize];
    ["Offset of field: weapon_data_s::fuser2"][offset_of!(weapon_data_s, fuser2) - 76usize];
    ["Offset of field: weapon_data_s::fuser3"][offset_of!(weapon_data_s, fuser3) - 80usize];
    ["Offset of field: weapon_data_s::fuser4"][offset_of!(weapon_data_s, fuser4) - 84usize];
};
pub type weapon_data_t = weapon_data_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct local_state_s {
    pub playerstate: entity_state_t,
    pub client: clientdata_t,
    pub weapondata: [weapon_data_t; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of local_state_s"][size_of::<local_state_s>() - 6448usize];
    ["Alignment of local_state_s"][align_of::<local_state_s>() - 4usize];
    ["Offset of field: local_state_s::playerstate"]
        [offset_of!(local_state_s, playerstate) - 0usize];
    ["Offset of field: local_state_s::client"][offset_of!(local_state_s, client) - 340usize];
    ["Offset of field: local_state_s::weapondata"]
        [offset_of!(local_state_s, weapondata) - 816usize];
};
pub type local_state_t = local_state_s;
