// bindgen halflife/common/particledef.h --allowlist-type "particle_t" --
// --target=i686-unknown-linux-gnu -Ihalflife/{public,common,engine} -include mathlib.h -include
// const.h
// Keep everything before the generated part
// Remove `vec_t` and `vec3_t` and replace `vec3_t` with `[f32; 3]`
// Remove the unnecessary qualifiers `::std::os::raw::`, `::std::mem::` and `::std::option::`

#![allow(nonstandard_style)]

use std::mem::{align_of, offset_of, size_of};
use std::option::Option;
use std::os::raw::*;

/* automatically generated by rust-bindgen 0.72.1 */

#[doc = "\tCopyright (c) 1996-2002, Valve LLC. All rights reserved.\n\n\tThis product contains software technology licensed from Id\n\tSoftware, Inc. (\"Id Technology\").  Id Technology (c) 1996 Id Software, Inc.\n\tAll Rights Reserved.\n\n   Use, distribution, and modification of this source code and/or resulting\n   object code is restricted to non-commercial enhancements to products from\n   Valve LLC.  All other use, distribution, or modification is prohibited\n   without written permission from Valve LLC."]
pub const ptype_t_pt_static: ptype_t = 0;
pub const ptype_t_pt_grav: ptype_t = 1;
pub const ptype_t_pt_slowgrav: ptype_t = 2;
pub const ptype_t_pt_fire: ptype_t = 3;
pub const ptype_t_pt_explode: ptype_t = 4;
pub const ptype_t_pt_explode2: ptype_t = 5;
pub const ptype_t_pt_blob: ptype_t = 6;
pub const ptype_t_pt_blob2: ptype_t = 7;
pub const ptype_t_pt_vox_slowgrav: ptype_t = 8;
pub const ptype_t_pt_vox_grav: ptype_t = 9;
pub const ptype_t_pt_clientcustom: ptype_t = 10;
pub type ptype_t = c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct particle_s {
    pub org: [f32; 3],
    pub color: c_short,
    pub packedColor: c_short,
    pub next: *mut particle_s,
    pub vel: [f32; 3],
    pub ramp: f32,
    pub die: f32,
    pub type_: ptype_t,
    pub deathfunc: Option<unsafe extern "C" fn(particle: *mut particle_s)>,
    pub callback: Option<unsafe extern "C" fn(particle: *mut particle_s, frametime: f32)>,
    pub context: c_uchar,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of particle_s"][size_of::<particle_s>() - 56usize];
    ["Alignment of particle_s"][align_of::<particle_s>() - 4usize];
    ["Offset of field: particle_s::org"][offset_of!(particle_s, org) - 0usize];
    ["Offset of field: particle_s::color"][offset_of!(particle_s, color) - 12usize];
    ["Offset of field: particle_s::packedColor"][offset_of!(particle_s, packedColor) - 14usize];
    ["Offset of field: particle_s::next"][offset_of!(particle_s, next) - 16usize];
    ["Offset of field: particle_s::vel"][offset_of!(particle_s, vel) - 20usize];
    ["Offset of field: particle_s::ramp"][offset_of!(particle_s, ramp) - 32usize];
    ["Offset of field: particle_s::die"][offset_of!(particle_s, die) - 36usize];
    ["Offset of field: particle_s::type_"][offset_of!(particle_s, type_) - 40usize];
    ["Offset of field: particle_s::deathfunc"][offset_of!(particle_s, deathfunc) - 44usize];
    ["Offset of field: particle_s::callback"][offset_of!(particle_s, callback) - 48usize];
    ["Offset of field: particle_s::context"][offset_of!(particle_s, context) - 52usize];
};
pub type particle_t = particle_s;
