// bindgen halflife/engine/progs.h --allowlist-type "event_state_t" --
// --target=i686-unknown-linux-gnu -Ihalflife/{public,common,engine,pm_shared} -include mathlib.h
// -include const.h
// Keep everything before the generated part
// Remove the unnecessary qualifiers `::std::os::raw::` and `::std::mem::`

#![allow(nonstandard_style)]

use std::mem::{align_of, offset_of, size_of};
use std::os::raw::*;

/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct event_args_s {
    pub flags: c_int,
    pub entindex: c_int,
    pub origin: [f32; 3usize],
    pub angles: [f32; 3usize],
    pub velocity: [f32; 3usize],
    pub ducking: c_int,
    pub fparam1: f32,
    pub fparam2: f32,
    pub iparam1: c_int,
    pub iparam2: c_int,
    pub bparam1: c_int,
    pub bparam2: c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of event_args_s"][size_of::<event_args_s>() - 72usize];
    ["Alignment of event_args_s"][align_of::<event_args_s>() - 4usize];
    ["Offset of field: event_args_s::flags"][offset_of!(event_args_s, flags) - 0usize];
    ["Offset of field: event_args_s::entindex"][offset_of!(event_args_s, entindex) - 4usize];
    ["Offset of field: event_args_s::origin"][offset_of!(event_args_s, origin) - 8usize];
    ["Offset of field: event_args_s::angles"][offset_of!(event_args_s, angles) - 20usize];
    ["Offset of field: event_args_s::velocity"][offset_of!(event_args_s, velocity) - 32usize];
    ["Offset of field: event_args_s::ducking"][offset_of!(event_args_s, ducking) - 44usize];
    ["Offset of field: event_args_s::fparam1"][offset_of!(event_args_s, fparam1) - 48usize];
    ["Offset of field: event_args_s::fparam2"][offset_of!(event_args_s, fparam2) - 52usize];
    ["Offset of field: event_args_s::iparam1"][offset_of!(event_args_s, iparam1) - 56usize];
    ["Offset of field: event_args_s::iparam2"][offset_of!(event_args_s, iparam2) - 60usize];
    ["Offset of field: event_args_s::bparam1"][offset_of!(event_args_s, bparam1) - 64usize];
    ["Offset of field: event_args_s::bparam2"][offset_of!(event_args_s, bparam2) - 68usize];
};
pub type event_args_t = event_args_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct event_info_s {
    pub index: c_ushort,
    pub packet_index: c_short,
    pub entity_index: c_short,
    pub fire_time: f32,
    pub args: event_args_t,
    pub flags: c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of event_info_s"][size_of::<event_info_s>() - 88usize];
    ["Alignment of event_info_s"][align_of::<event_info_s>() - 4usize];
    ["Offset of field: event_info_s::index"][offset_of!(event_info_s, index) - 0usize];
    ["Offset of field: event_info_s::packet_index"]
        [offset_of!(event_info_s, packet_index) - 2usize];
    ["Offset of field: event_info_s::entity_index"]
        [offset_of!(event_info_s, entity_index) - 4usize];
    ["Offset of field: event_info_s::fire_time"][offset_of!(event_info_s, fire_time) - 8usize];
    ["Offset of field: event_info_s::args"][offset_of!(event_info_s, args) - 12usize];
    ["Offset of field: event_info_s::flags"][offset_of!(event_info_s, flags) - 84usize];
};
pub type event_state_t = event_state_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct event_state_s {
    pub ei: [event_info_s; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of event_state_s"][size_of::<event_state_s>() - 5632usize];
    ["Alignment of event_state_s"][align_of::<event_state_s>() - 4usize];
    ["Offset of field: event_state_s::ei"][offset_of!(event_state_s, ei) - 0usize];
};
