// bindgen halflife/common/r_efx.h --allowlist-type "TEMPENTITY" -- --target=i686-unknown-linux-gnu
// -Ihalflife/{public,common,engine,pm_shared} -include mathlib.h -include const.h
// Keep everything before the generated part
// Remove `model_s` dummy struct and import `model_s` from com_model.rs
// Remove `mleaf_s` dummy struct and import `mleaf_s` from com_model.rs
// Remove `mnode_s` dummy struct and import `mnode_s` from com_model.rs
// Remove `pmtrace_s` dummy struct and import `pmtrace_s` from pmtrace.rs
// Remove generated `cl_entity_s` and `position_history_t` import `cl_entity_s` from entity_state.rs
// Remove generated `entity_state_t` import `entity_state_t` from entity_state.rs
// Remove `vec_t` and `vec3_t` and replace `vec3_t` with `[f32; 3]`
// Remove the unnecessary qualifiers `::std::os::raw::`, `::std::mem::` and `::std::option::`

#![allow(unused, nonstandard_style)]

use std::mem::{align_of, offset_of, size_of};
use std::option::Option;
use std::os::raw::*;

use super::cl_entity::{cl_entity_s, cl_entity_t};
use super::com_model::{mleaf_s, mnode_s, model_s};
use super::entity_state::entity_state_t;
use super::pmtrace::pmtrace_s;

/* automatically generated by rust-bindgen 0.72.1 */

#[doc = "\tCopyright (c) 1996-2002, Valve LLC. All rights reserved.\n\n\tThis product contains software technology licensed from Id\n\tSoftware, Inc. (\"Id Technology\").  Id Technology (c) 1996 Id Software, Inc.\n\tAll Rights Reserved.\n\n   Use, distribution, and modification of this source code and/or resulting\n   object code is restricted to non-commercial enhancements to products from\n   Valve LLC.  All other use, distribution, or modification is prohibited\n   without written permission from Valve LLC."]
pub type byte = c_uchar;
pub const qboolean_false_: qboolean = 0;
pub const qboolean_true_: qboolean = 1;
pub type qboolean = c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct color24 {
    pub r: byte,
    pub g: byte,
    pub b: byte,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of color24"][size_of::<color24>() - 3usize];
    ["Alignment of color24"][align_of::<color24>() - 1usize];
    ["Offset of field: color24::r"][offset_of!(color24, r) - 0usize];
    ["Offset of field: color24::g"][offset_of!(color24, g) - 1usize];
    ["Offset of field: color24::b"][offset_of!(color24, b) - 2usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct colorVec {
    pub r: c_uint,
    pub g: c_uint,
    pub b: c_uint,
    pub a: c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of colorVec"][size_of::<colorVec>() - 16usize];
    ["Alignment of colorVec"][align_of::<colorVec>() - 4usize];
    ["Offset of field: colorVec::r"][offset_of!(colorVec, r) - 0usize];
    ["Offset of field: colorVec::g"][offset_of!(colorVec, g) - 4usize];
    ["Offset of field: colorVec::b"][offset_of!(colorVec, b) - 8usize];
    ["Offset of field: colorVec::a"][offset_of!(colorVec, a) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct efrag_s {
    pub leaf: *mut mleaf_s,
    pub leafnext: *mut efrag_s,
    pub entity: *mut cl_entity_s,
    pub entnext: *mut efrag_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of efrag_s"][size_of::<efrag_s>() - 16usize];
    ["Alignment of efrag_s"][align_of::<efrag_s>() - 4usize];
    ["Offset of field: efrag_s::leaf"][offset_of!(efrag_s, leaf) - 0usize];
    ["Offset of field: efrag_s::leafnext"][offset_of!(efrag_s, leafnext) - 4usize];
    ["Offset of field: efrag_s::entity"][offset_of!(efrag_s, entity) - 8usize];
    ["Offset of field: efrag_s::entnext"][offset_of!(efrag_s, entnext) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mouth_t {
    pub mouthopen: byte,
    pub sndcount: byte,
    pub sndavg: c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mouth_t"][size_of::<mouth_t>() - 8usize];
    ["Alignment of mouth_t"][align_of::<mouth_t>() - 4usize];
    ["Offset of field: mouth_t::mouthopen"][offset_of!(mouth_t, mouthopen) - 0usize];
    ["Offset of field: mouth_t::sndcount"][offset_of!(mouth_t, sndcount) - 1usize];
    ["Offset of field: mouth_t::sndavg"][offset_of!(mouth_t, sndavg) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct latchedvars_t {
    pub prevanimtime: f32,
    pub sequencetime: f32,
    pub prevseqblending: [byte; 2usize],
    pub prevorigin: [f32; 3],
    pub prevangles: [f32; 3],
    pub prevsequence: c_int,
    pub prevframe: f32,
    pub prevcontroller: [byte; 4usize],
    pub prevblending: [byte; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of latchedvars_t"][size_of::<latchedvars_t>() - 52usize];
    ["Alignment of latchedvars_t"][align_of::<latchedvars_t>() - 4usize];
    ["Offset of field: latchedvars_t::prevanimtime"]
        [offset_of!(latchedvars_t, prevanimtime) - 0usize];
    ["Offset of field: latchedvars_t::sequencetime"]
        [offset_of!(latchedvars_t, sequencetime) - 4usize];
    ["Offset of field: latchedvars_t::prevseqblending"]
        [offset_of!(latchedvars_t, prevseqblending) - 8usize];
    ["Offset of field: latchedvars_t::prevorigin"][offset_of!(latchedvars_t, prevorigin) - 12usize];
    ["Offset of field: latchedvars_t::prevangles"][offset_of!(latchedvars_t, prevangles) - 24usize];
    ["Offset of field: latchedvars_t::prevsequence"]
        [offset_of!(latchedvars_t, prevsequence) - 36usize];
    ["Offset of field: latchedvars_t::prevframe"][offset_of!(latchedvars_t, prevframe) - 40usize];
    ["Offset of field: latchedvars_t::prevcontroller"]
        [offset_of!(latchedvars_t, prevcontroller) - 44usize];
    ["Offset of field: latchedvars_t::prevblending"]
        [offset_of!(latchedvars_t, prevblending) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tempent_s {
    pub flags: c_int,
    pub die: f32,
    pub frameMax: f32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub fadeSpeed: f32,
    pub bounceFactor: f32,
    pub hitSound: c_int,
    pub hitcallback: Option<unsafe extern "C" fn(ent: *mut tempent_s, ptr: *mut pmtrace_s)>,
    pub callback:
        Option<unsafe extern "C" fn(ent: *mut tempent_s, frametime: f32, currenttime: f32)>,
    pub next: *mut tempent_s,
    pub priority: c_int,
    pub clientIndex: c_short,
    pub tentOffset: [f32; 3],
    pub entity: cl_entity_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tempent_s"][size_of::<tempent_s>() - 3068usize];
    ["Alignment of tempent_s"][align_of::<tempent_s>() - 4usize];
    ["Offset of field: tempent_s::flags"][offset_of!(tempent_s, flags) - 0usize];
    ["Offset of field: tempent_s::die"][offset_of!(tempent_s, die) - 4usize];
    ["Offset of field: tempent_s::frameMax"][offset_of!(tempent_s, frameMax) - 8usize];
    ["Offset of field: tempent_s::x"][offset_of!(tempent_s, x) - 12usize];
    ["Offset of field: tempent_s::y"][offset_of!(tempent_s, y) - 16usize];
    ["Offset of field: tempent_s::z"][offset_of!(tempent_s, z) - 20usize];
    ["Offset of field: tempent_s::fadeSpeed"][offset_of!(tempent_s, fadeSpeed) - 24usize];
    ["Offset of field: tempent_s::bounceFactor"][offset_of!(tempent_s, bounceFactor) - 28usize];
    ["Offset of field: tempent_s::hitSound"][offset_of!(tempent_s, hitSound) - 32usize];
    ["Offset of field: tempent_s::hitcallback"][offset_of!(tempent_s, hitcallback) - 36usize];
    ["Offset of field: tempent_s::callback"][offset_of!(tempent_s, callback) - 40usize];
    ["Offset of field: tempent_s::next"][offset_of!(tempent_s, next) - 44usize];
    ["Offset of field: tempent_s::priority"][offset_of!(tempent_s, priority) - 48usize];
    ["Offset of field: tempent_s::clientIndex"][offset_of!(tempent_s, clientIndex) - 52usize];
    ["Offset of field: tempent_s::tentOffset"][offset_of!(tempent_s, tentOffset) - 56usize];
    ["Offset of field: tempent_s::entity"][offset_of!(tempent_s, entity) - 68usize];
};
pub type TEMPENTITY = tempent_s;
