// bindgen halflife/common/screenfade.h --allowlist-type "screenfade_t" --
// --target=i686-unknown-linux-gnu -Ihalflife/{public,common,engine} -include mathlib.h -include
// const.h
// Keep everything before the generated part
// Remove the unnecessary qualifiers `::std::os::raw::` and `::std::mem::`
// Remove `vec_t` and `vec3_t` and replace `vec3_t` with `[f32; 3]`

#![allow(unused, nonstandard_style)]

use std::mem::offset_of;
use std::os::raw::*;

/* automatically generated by rust-bindgen 0.72.1 */

pub type byte = c_uchar;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct screenfade_s {
    pub fadeSpeed: f32,
    pub fadeEnd: f32,
    pub fadeTotalEnd: f32,
    pub fadeReset: f32,
    pub fader: byte,
    pub fadeg: byte,
    pub fadeb: byte,
    pub fadealpha: byte,
    pub fadeFlags: c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of screenfade_s"][size_of::<screenfade_s>() - 24usize];
    ["Alignment of screenfade_s"][align_of::<screenfade_s>() - 4usize];
    ["Offset of field: screenfade_s::fadeSpeed"][offset_of!(screenfade_s, fadeSpeed) - 0usize];
    ["Offset of field: screenfade_s::fadeEnd"][offset_of!(screenfade_s, fadeEnd) - 4usize];
    ["Offset of field: screenfade_s::fadeTotalEnd"]
        [offset_of!(screenfade_s, fadeTotalEnd) - 8usize];
    ["Offset of field: screenfade_s::fadeReset"][offset_of!(screenfade_s, fadeReset) - 12usize];
    ["Offset of field: screenfade_s::fader"][offset_of!(screenfade_s, fader) - 16usize];
    ["Offset of field: screenfade_s::fadeg"][offset_of!(screenfade_s, fadeg) - 17usize];
    ["Offset of field: screenfade_s::fadeb"][offset_of!(screenfade_s, fadeb) - 18usize];
    ["Offset of field: screenfade_s::fadealpha"][offset_of!(screenfade_s, fadealpha) - 19usize];
    ["Offset of field: screenfade_s::fadeFlags"][offset_of!(screenfade_s, fadeFlags) - 20usize];
};
pub type screenfade_t = screenfade_s;
