// bindgen halflife/common/weaponinfo.h --allowlist-type "weapon_data_t" --
// --target=i686-unknown-linux-gnu -Ihalflife/{public,common,engine} -include mathlib.h -include
// const.h
// Keep everything before the generated part
// Remove the unnecessary qualifiers `::std::os::raw::` and `::std::mem::`

#![allow(nonstandard_style)]

use std::mem::{align_of, offset_of, size_of};
use std::os::raw::*;

/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct weapon_data_s {
    pub m_iId: c_int,
    pub m_iClip: c_int,
    pub m_flNextPrimaryAttack: f32,
    pub m_flNextSecondaryAttack: f32,
    pub m_flTimeWeaponIdle: f32,
    pub m_fInReload: c_int,
    pub m_fInSpecialReload: c_int,
    pub m_flNextReload: f32,
    pub m_flPumpTime: f32,
    pub m_fReloadTime: f32,
    pub m_fAimedDamage: f32,
    pub m_fNextAimBonus: f32,
    pub m_fInZoom: c_int,
    pub m_iWeaponState: c_int,
    pub iuser1: c_int,
    pub iuser2: c_int,
    pub iuser3: c_int,
    pub iuser4: c_int,
    pub fuser1: f32,
    pub fuser2: f32,
    pub fuser3: f32,
    pub fuser4: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of weapon_data_s"][size_of::<weapon_data_s>() - 88usize];
    ["Alignment of weapon_data_s"][align_of::<weapon_data_s>() - 4usize];
    ["Offset of field: weapon_data_s::m_iId"][offset_of!(weapon_data_s, m_iId) - 0usize];
    ["Offset of field: weapon_data_s::m_iClip"][offset_of!(weapon_data_s, m_iClip) - 4usize];
    ["Offset of field: weapon_data_s::m_flNextPrimaryAttack"]
        [offset_of!(weapon_data_s, m_flNextPrimaryAttack) - 8usize];
    ["Offset of field: weapon_data_s::m_flNextSecondaryAttack"]
        [offset_of!(weapon_data_s, m_flNextSecondaryAttack) - 12usize];
    ["Offset of field: weapon_data_s::m_flTimeWeaponIdle"]
        [offset_of!(weapon_data_s, m_flTimeWeaponIdle) - 16usize];
    ["Offset of field: weapon_data_s::m_fInReload"]
        [offset_of!(weapon_data_s, m_fInReload) - 20usize];
    ["Offset of field: weapon_data_s::m_fInSpecialReload"]
        [offset_of!(weapon_data_s, m_fInSpecialReload) - 24usize];
    ["Offset of field: weapon_data_s::m_flNextReload"]
        [offset_of!(weapon_data_s, m_flNextReload) - 28usize];
    ["Offset of field: weapon_data_s::m_flPumpTime"]
        [offset_of!(weapon_data_s, m_flPumpTime) - 32usize];
    ["Offset of field: weapon_data_s::m_fReloadTime"]
        [offset_of!(weapon_data_s, m_fReloadTime) - 36usize];
    ["Offset of field: weapon_data_s::m_fAimedDamage"]
        [offset_of!(weapon_data_s, m_fAimedDamage) - 40usize];
    ["Offset of field: weapon_data_s::m_fNextAimBonus"]
        [offset_of!(weapon_data_s, m_fNextAimBonus) - 44usize];
    ["Offset of field: weapon_data_s::m_fInZoom"][offset_of!(weapon_data_s, m_fInZoom) - 48usize];
    ["Offset of field: weapon_data_s::m_iWeaponState"]
        [offset_of!(weapon_data_s, m_iWeaponState) - 52usize];
    ["Offset of field: weapon_data_s::iuser1"][offset_of!(weapon_data_s, iuser1) - 56usize];
    ["Offset of field: weapon_data_s::iuser2"][offset_of!(weapon_data_s, iuser2) - 60usize];
    ["Offset of field: weapon_data_s::iuser3"][offset_of!(weapon_data_s, iuser3) - 64usize];
    ["Offset of field: weapon_data_s::iuser4"][offset_of!(weapon_data_s, iuser4) - 68usize];
    ["Offset of field: weapon_data_s::fuser1"][offset_of!(weapon_data_s, fuser1) - 72usize];
    ["Offset of field: weapon_data_s::fuser2"][offset_of!(weapon_data_s, fuser2) - 76usize];
    ["Offset of field: weapon_data_s::fuser3"][offset_of!(weapon_data_s, fuser3) - 80usize];
    ["Offset of field: weapon_data_s::fuser4"][offset_of!(weapon_data_s, fuser4) - 84usize];
};
pub type weapon_data_t = weapon_data_s;
